### ISSUE TITLE
Consider adding a licence to this repo

### ISSUE THREAD

**Issue by ksa-real** [acoustid/ffmpeg-build#5]
I'd like to use the build-linux.sh file to build the libraries for Apline. Would you add some license for the repo? Thanks

**Comment by lalinsky** [comment]
You can consider the repo MIT licensed

**Comment by lalinsky** [comment]
https://github.com/acoustid/ffmpeg-build/commit/7cfc37f7ffdd655809fba829cbc474fd2b1aef40
